### PR TITLE
Adding Full Translation Support

### PR DESCRIPTION
**Pull request by SparkyCloudy**
:3

### CODE REVIEW

**Review by oylsister — CHANGES_REQUESTED** [review]
Make sure to pull origin for latest update first

**Review by SparkyCloudy — COMMENTED** [review]
added more command for hkp2000, decoy, and flashbang

**Review by SparkyCloudy — COMMENTED** [review]
this one already with the current from your main  branch + mFull translation support

**Review by SparkyCloudy — COMMENTED** [review]
alrite this one dont include the smx, i put wrong compiled version, should i compile it?

**Pull request closed without merging**
